**<h1 align='middle'><font color = 'red'>Matrix Decomposition</font></h1>**
Matrix decomposition is a technique for reducing a matrix into a product of simpler matrices. This can be useful for a variety of reasons, such as:

- Simplifying matrix operations: Many matrix operations are much easier to perform on decomposed matrices. For example, the determinant of a matrix can be computed very quickly if the matrix is in its LU decomposition form.
- Reducing the size of a matrix: Decomposing a matrix can sometimes reduce its size, which can make it faster to store and manipulate. For example, the SVD of a matrix can be used to reduce its size by a factor of two.
- Uncovering hidden structure: Matrix decomposition can sometimes reveal hidden structure in a matrix. For example, the eigenvectors of a matrix can be used to find the directions in which the matrix stretches or compresses data.

There are many different types of matrix decompositions, each of which has its own advantages and disadvantages. Some of the most common types of matrix decompositions include:

- **LU decomposition**: This decomposition breaks a matrix down into a product of a lower triangular matrix and an upper triangular matrix. LU decomposition is very useful for solving linear systems of equations and for computing the determinant of a matrix.
- **QR decomposition**
- **Eigendecomposition**
- **SVD(Singular Value Decomposition)**: This decomposition breaks a matrix down into a product of a three matrices: a left singular matrix, a diagonal matrix of singular values, and a right singular matrix. SVD is very useful for data compression and for finding hidden structure in data.
- **Cholesky decomposition**: This decomposition is only applicable to positive-definite matrices. It breaks a matrix down into a product of a lower triangular matrix and its transpose. Cholesky decomposition is very useful for solving linear systems of equations and for computing the determinant of a matrix.
- **Schur decomposition**: This decomposition is only applicable to normal matrices. It breaks a matrix down into a product of a unitary matrix and a triangular matrix. Schur decomposition is very useful for finding eigenvalues and eigenvectors of a matrix.

# **<font color = 'red'>LU Decomposition</font>**
LU decomposition, also known as lower-upper decomposition, is a matrix factorization method that decomposes a matrix into a product of a lower triangular matrix and an upper triangular matrix. The LU decomposition can be used to solve systems of linear equations, compute the determinant of a matrix, and invert a matrix.

A = LU

- **P**: a permutation matrix is a square binary matrix that has exactly one entry of 1 in each row and each column and 0s elsewhere
- **L**: A lower triangular matrix is a square matrix in which all the entries above the main diagonal are zero  
-> all elements are valued at lower side
- **U**: An upper triangular matrix is a square matrix in which all the entries below the main diagonal are zero  
-> all elements are valued at upper side

The product of P, L, U matrix is equal to original matrix A.

In [1]:
from numpy import array
from scipy.linalg import lu

In [2]:
A = array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [3]:
P, L, U = lu(A)

In [4]:
P

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.]])

In [5]:
L

array([[1.        , 0.        , 0.        ],
       [0.14285714, 1.        , 0.        ],
       [0.57142857, 0.5       , 1.        ]])

In [6]:
U

array([[7.        , 8.        , 9.        ],
       [0.        , 0.85714286, 1.71428571],
       [0.        , 0.        , 0.        ]])

In [7]:
B = P.dot(L).dot(U)
B

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

$\text{We can see that matrix B = P.L.U has the same result of the original matrix.}$

# **<font color = 'red'>QR Decomposition</font>**
The QR decomposition is for 𝑚 × 𝑛 matrices (not limited to square
matrices) and decomposes a matrix into 𝑄 and 𝑅 components.

𝐴 = 𝑄.𝑅

It is also known as a QR factorization or QU factorization, is a decomposition of a matrix A into a product A = QR of **an orthonormal matrix(Q)** and **an upper triangular matrix(R)**.

- An orthonormal matrix is a matrix whose columns and rows are orthonormal vectors. Orthonormal vectors are vectors that are perpendicular to each other and have a length of 1.
- An upper triangular matrix is a matrix in which all the elements below the main diagonal are zero.

In [1]:
from numpy import array
from numpy.linalg import qr

In [3]:
A = array([[1,2],
          [3,4], 
          [5,6]])
A

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
Q, R = qr(A, 'complete')

In [6]:
Q

array([[-0.16903085,  0.89708523,  0.40824829],
       [-0.50709255,  0.27602622, -0.81649658],
       [-0.84515425, -0.34503278,  0.40824829]])

In [7]:
R

array([[-5.91607978, -7.43735744],
       [ 0.        ,  0.82807867],
       [ 0.        ,  0.        ]])

In [8]:
B = Q.dot(R)
B

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

# **<font color = 'red'>Eigendecomposition</font>**
In linear algebra, eigendecomposition, also known as spectral decomposition, is a factorization of a matrix into a canonical form, whereby the matrix is represented in terms of its eigenvalues and eigenvectors. Only diagonalizable matrices can be factorized in this way.

A = U.D.V^T

- U is an orthonormal matrix whose columns are the eigenvectors of A
- D is a diagonal matrix whose diagonal elements are the eigenvalues of A
- V^T is the transpose of U

In [9]:
import numpy as np

In [12]:
def eigendecomposition(A):
  """
  Calculates the eigendecomposition of a matrix.

  Args:
    A: The matrix to decompose.

  Returns:
    A tuple of the eigenvalues and eigenvectors of A.
  """

  # Check if A is square.
  if A.shape[0] != A.shape[1]:
    raise ValueError("A must be a square matrix.")

  # Calculate the eigenvalues and eigenvectors of A.
  eigenvalues, eigenvectors = np.linalg.eig(A)

  # Return the eigenvalues and eigenvectors.
  return eigenvalues, eigenvectors
A = array([[1,2,3], 
           [4,5,6], 
           [7,8,9]])
eigendecomposition(A)

(array([ 1.61168440e+01, -1.11684397e+00, -9.75918483e-16]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

# **<font color = 'red'>SVD(Singular Value Decomposition)</font>**

In linear algebra, singular value decomposition (SVD) is a factorization of a real or complex square matrix into three matrices: a product of a left singular matrix, a diagonal matrix of singular values, and a right singular matrix. The SVD of an m×n real or complex matrix A is expressed as

$$ A = U \Sigma V^T $$

where:

- U is an m×m real or complex orthogonal matrix (unitary matrix)
- Σ is an m×n diagonal matrix whose diagonal elements are the singular values of A, arranged in descending order of magnitude
- V is an n×n real or complex orthogonal matrix (unitary matrix)

In [19]:
def svd(A):
  """
  Calculates the singular value decomposition of a matrix.

  Args:
    A: The matrix to decompose.

  Returns:
    A tuple of the left singular matrix, the diagonal matrix of singular values, and the right singular matrix.
  """

  # Check if A is square.
  if A.shape[0] != A.shape[1]:
    raise ValueError("A must be a square matrix.")

  # Calculate the SVD of A.
  U, s, Vh = np.linalg.svd(A)

  # Return the SVD of A.
  return U, s, Vh
A = array([[1,2,3], 
           [4,5,6], 
           [7,8,9]])
svd(A)

(array([[-0.21483724,  0.88723069,  0.40824829],
        [-0.52058739,  0.24964395, -0.81649658],
        [-0.82633754, -0.38794278,  0.40824829]]),
 array([1.68481034e+01, 1.06836951e+00, 3.33475287e-16]),
 array([[-0.47967118, -0.57236779, -0.66506441],
        [-0.77669099, -0.07568647,  0.62531805],
        [-0.40824829,  0.81649658, -0.40824829]]))

# **<font color = 'red'>Cholesky Decomposition</font>**
The Cholesky decomposition is for square symmetric matrices
where all values are greater than zero, so-called positive definite matrices.

𝐴 = 𝐿.𝐿^T

Where 𝐴 is the matrix being decomposed, 𝐿 is the lower triangular
matrix and 𝐿^T is the transpose of 𝐿.

In [13]:
from numpy import array
from numpy.linalg import cholesky

In [16]:
A = array([[2,1,1], 
           [1,2,1], 
           [1,1,2]])
A

array([[2, 1, 1],
       [1, 2, 1],
       [1, 1, 2]])

In [17]:
L = cholesky(A)
L

array([[1.41421356, 0.        , 0.        ],
       [0.70710678, 1.22474487, 0.        ],
       [0.70710678, 0.40824829, 1.15470054]])

In [18]:
B = L.dot(L.T)
B

array([[2., 1., 1.],
       [1., 2., 1.],
       [1., 1., 2.]])