**<h1 align='middle'><font color = 'red'>Matrix Decomposition</font></h1>**
<h1 align='middle'><font color = 'blue'>Name: Nang Sreynich</font></h1>
<h1 align='middle'><font color = 'blue'>ID: e20200447</font></h1>
<h1 align='middle'><font color = 'blue'>Group: I3_AMS_B</font></h1>

$\text{1. Find the SVD of the following matrix:}$ $$A = \begin{bmatrix} 3&2&2 \\ 2&3&-2 \end{bmatrix}$$
$$B = \begin{bmatrix} 2&2 \\ -1&1 \end{bmatrix}$$

In [18]:
import numpy as np
from scipy.linalg import svd
import numpy.linalg as la
import torch

In [2]:
A = np.array([[3, 2, 2], [2, 3, -2]])
A

array([[ 3,  2,  2],
       [ 2,  3, -2]])

In [3]:
U, s, Vt = np.linalg.svd(A)

In [4]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [5]:
s

array([5., 3.])

In [6]:
Vt

array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

In [7]:
B = np.array([[3, 2, 2], [2, 3, -2]])
B

array([[ 3,  2,  2],
       [ 2,  3, -2]])

In [8]:
U, s, Vt = np.linalg.svd(A)

In [9]:
U

array([[-0.70710678, -0.70710678],
       [-0.70710678,  0.70710678]])

In [10]:
s

array([5., 3.])

In [11]:
Vt

array([[-7.07106781e-01, -7.07106781e-01, -6.47932334e-17],
       [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
       [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]])

$\text{2. Using the matrix}$ $$P = \begin{bmatrix} 25&2&-5 \\ 3&-2&1 \\5&7&4 \end{bmatrix}$$ 
$\text{from the proceeding PyTorch exercises, demonstrate that these three SVD-eigendecomposition equations are true}$

In [12]:
P = np.array([[25, 2, -5], [3, -2, 1], [5, 7, 4]])
P

array([[25,  2, -5],
       [ 3, -2,  1],
       [ 5,  7,  4]])

In [13]:
U, S, V = svd(P)

In [14]:
U

array([[-0.97571953,  0.18227289,  0.1214413 ],
       [-0.09750433,  0.1350092 , -0.9860352 ],
       [-0.19612318, -0.97393486, -0.11395871]])

In [15]:
S

array([26.16323489,  8.1875465 ,  2.53953194])

In [16]:
V

array([[-0.98099938, -0.11960649,  0.15275636],
       [ 0.01125803, -0.82112714, -0.57063428],
       [-0.19368396,  0.55807214, -0.80687174]])

In [17]:
Sigma = np.diag(S)
Sigma

array([[26.16323489,  0.        ,  0.        ],
       [ 0.        ,  8.1875465 ,  0.        ],
       [ 0.        ,  0.        ,  2.53953194]])

$\text{3. Use the torch.svd() method to calculate the pseudoinverse of Ap, confirming that your results matches the output of torch.pinverse(Ap)}$ 

In [19]:
A = torch.tensor([[3.0, 2.0, 2.0], [2.0, 3.0, -2.0]])
P = torch.tensor([[25.0, 2.0, -5.0], [3.0, -2.0, 1.0], [5.0, 7.0, 4.0]])

# Compute the product Ap
Ap = torch.matmul(A, P)

# Calculate the pseudoinverse of Ap using torch.svd()
U, S, V = torch.svd(Ap)

pseudoinv_svd = torch.matmul(V, torch.matmul(torch.diag(S.reciprocal()), U.t()))
print(f'\nThe result of the pseudoinverse of Ap using torch.svd() \n{pseudoinv_svd}')

# Calculate the pseudoinverse of Ap using torch.pinverse()
pseudoinv_pinv = torch.pinverse(Ap)
print(f'\nThe result of the pseudoinverse of Ap using torch.pinverse() \n{pseudoinv_pinv}')

# Compare the results
print(f'\nCompare the result is {torch.allclose(pseudoinv_svd, pseudoinv_pinv)}') 


The result of the pseudoinverse of Ap using torch.svd() 
tensor([[ 0.0083,  0.0047],
        [ 0.0180, -0.0322],
        [ 0.0078, -0.0168]])

The result of the pseudoinverse of Ap using torch.pinverse() 
tensor([[ 0.0083,  0.0047],
        [ 0.0180, -0.0322],
        [ 0.0078, -0.0168]])

Compare the result is True


$\text{4. With the Ap provided below:}$ $$A = \begin{bmatrix} -1&2 \\ 3&-2 \\5&7 \end{bmatrix}$$ 
$\text{(a) Use the PyTorch trace method to calculate the trace of Ap}$

In [20]:
# Define matrix A
A = torch.tensor([[-1.0, 2.0, 3.0], [-2.0, 5.0, 7.0]])

# Define matrix p
P = torch.tensor([[25.0, 2.0, -5.0], [3.0, -2.0, 1.0], [5.0, 7.0, 4.0]])

# Compute the product Ap
Ap = torch.matmul(A, P)

# Calculate the trace of Ap using the trace() method
trace_Ap = torch.trace(Ap)

# Print the result
print(f'The trace of Ap is {trace_Ap}') 

The trace of Ap is 31.0


$\text{(b) Use the PyTorch Frobenius norm method and the race method to demonstrate that ∥A∥F=sqrt(Tr(AAT)).}$

In [21]:
# Define matrix A
A = torch.tensor([[-1.0, 2.0, 3.0], [-2.0, 5.0, 7.0]])

# Calculate the Frobenius norm of A using the norm() method
frobenius_norm_A = torch.norm(A, p='fro')
print(f'The Frobenius norm of matrix A is {frobenius_norm_A}\n')

# Calculate Tr(AAT) using the trace() method
trace_AAT = torch.trace(torch.matmul(A, A.t()))
print(f'The value of Tr(AAT) \n{trace_AAT}\n')

# Calculate sqrt(Tr(AAT))
sqrt_trace_AAT = torch.sqrt(trace_AAT)
print(f'\nThe sqrt root of Tr(AAT) is {sqrt_trace_AAT}\n')

# Compare the two results
print(torch.allclose(frobenius_norm_A, sqrt_trace_AAT))

The Frobenius norm of matrix A is 9.591663360595703

The value of Tr(AAT) 
92.0


The sqrt root of Tr(AAT) is 9.591663360595703

True
